### PR TITLE
add dingo

### PR DESCRIPTION
**Pull request by Jokrasa1011**
Changed the file structure and copied missing files from jackal as described in the discord message. 

Gazebo and rviz launch and the robot is loaded but the robot does not move and I get the following warning: 

[ WARN] [1700058193.090380268, 5.016000000]: Covariance matrix is not positive (semi-)definite in ProbabilityEllipseCovarianceVisual::setMeanCovariance(): Matrix3(0, 0, 0, 0, 0, 0, 0, 0, 0)
[ WARN] [1700058195.148084803, 7.066000000]: Timed out waiting for transform from dingo/link_base to odom to become available before running costmap, tf error: canTransform: source_frame dingo/link_base does not exist.. canTransform returned after 0.1 timeout was 0.1.

@voshch

### CODE REVIEW

**Review by Jokrasa1011 — COMMENTED** [review]
c29dc05 should propably be in another pull request as it is for the laikago robot, I accidentally added it to this request, how can I fix this?

Laikago is not working as  laikago_description is missing / cant be found:

resource not found: laikago_description
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/jonas/arena_ws/src
ROS path [2]=/opt/ros/noetic/share
when processing file: /home/jonas/arena_ws/src/arena-simulation-setup/robot/laikago/urdf/laikago.urdf.xacro

**Comment by Jokrasa1011** [comment]
I fixed the base_link bug as described in discord.

Then the robot moved very slowly and uncoordinated with the Warning "Goal off global costmap". 

I fixed this by replacing global_costmap_params with global_costmap_params from the jackal folder - not sure if this is an okay solution but the robot seems to be working now. I will do more tests and record and upload them tomorrow and on Friday. 

@voshch

**Comment by voshch** [comment]
did not review laikago, open separate PR when ready

**Comment by voshch** [comment]
> [c29dc05](https://github.com/voshch/arena-simulation-setup/commit/c29dc057da9a78e9f4cbd521fefa1f88c2f677ac) should propably be in another pull request as it is for the laikago robot, I accidentally added it to this request, how can I fix this?
> 
> Laikago is not working as laikago_description is missing / cant be found:
> 
> resource not found: laikago_description ROS path [0]=/opt/ros/noetic/share/ros ROS path [1]=/home/jonas/arena_ws/src ROS path [2]=/opt/ros/noetic/share when processing file: /home/jonas/arena_ws/src/arena-simulation-setup/robot/laikago/urdf/laikago.urdf.xacro

replace `$(find laikago_description)` with `$(find arena-simulation-setup)/robot/laikago` and `package://laikago_description` with `package://arena-simulation-setup/robot/laikago`

**Pull request merged**
